"""Professional PDF report generation"""
import os
import io
import logging
from datetime import datetime
from typing import Dict, List
from reportlab.lib.pagesizes import A4, letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Image, KeepTogether
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.piecharts import Pie
from reportlab.graphics.charts.barcharts import VerticalBarChart
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from models import Scan, Finding, User, Organization

logger = logging.getLogger(__name__)


class PDFReportGenerator:
    """Generate professional PDF reports"""

    def __init__(self, scan: Scan, user: User, organization: Organization = None):
        self.scan = scan
        self.user = user
        self.organization = organization
        self.findings = Finding.query.filter_by(scan_id=scan.id).all()
        self.styles = getSampleStyleSheet()
        self._setup_styles()
        self.severity_colors = {0: colors.HexColor('#10b981'), 1: colors.HexColor('#3b82f6'), 2: colors.HexColor('#f59e0b'), 3: colors.HexColor('#ef4444'), 4: colors.HexColor('#dc2626')}
        self.severity_names = {0: 'Info', 1: 'Low', 2: 'Medium', 3: 'High', 4: 'Critical'}

    def _setup_styles(self):
        self.styles.add(ParagraphStyle(name='CustomTitle', parent=self.styles['Title'], fontSize=32, textColor=colors.HexColor('#6366f1'), spaceAfter=20, alignment=TA_CENTER))
        self.styles.add(ParagraphStyle(name='CustomHeading1', parent=self.styles['Heading1'], fontSize=20, textColor=colors.HexColor('#1e293b'), spaceAfter=15, spaceBefore=20))
        self.styles.add(ParagraphStyle(name='CustomHeading2', parent=self.styles['Heading2'], fontSize=14, textColor=colors.HexColor('#475569'), spaceAfter=10, spaceBefore=15))
        self.styles.add(ParagraphStyle(name='CustomBody', parent=self.styles['BodyText'], fontSize=10, alignment=TA_JUSTIFY, spaceAfter=8))
        self.styles.add(ParagraphStyle(name='CodeStyle', parent=self.styles['Code'], fontSize=8, leftIndent=20, backColor=colors.HexColor('#f1f5f9'), borderColor=colors.HexColor('#cbd5e1'), borderWidth=1, borderPadding=8))

    def generate(self, output_path: str = None) -> bytes:
        """Generate PDF report and return as bytes"""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4, rightMargin=2*cm, leftMargin=2*cm, topMargin=2*cm, bottomMargin=2*cm, title=f"Recon Scan Report - {self.scan.target}", author="KRYZENSYS")
        story = []
        story.extend(self._build_cover())
        story.append(PageBreak())
        story.extend(self._build_executive_summary())
        story.append(PageBreak())
        story.extend(self._build_target_info())
        story.extend(self._build_severity_overview())
        story.append(PageBreak())
        story.extend(self._build_findings())
        story.extend(self._build_recommendations())
        story.append(PageBreak())
        story.extend(self._build_appendix())
        doc.build(story, onFirstPage=self._draw_footer, onLaterPages=self._draw_footer)
        pdf_bytes = buffer.getvalue()
        if output_path:
            with open(output_path, 'wb') as f: f.write(pdf_bytes)
        return pdf_bytes

    def _build_cover(self) -> List:
        story = []
        story.append(Spacer(1, 3*cm))
        story.append(Paragraph("🛡️", self.styles['Title']))
        story.append(Paragraph("Security Scan Report", self.styles['CustomTitle']))
        story.append(Spacer(1, 0.5*cm))
        story.append(Paragraph(f"<b>{self.scan.target}</b>", self.styles['Heading2']))
        story.append(Spacer(1, 2*cm))
        cover_data = [
            ['Report Type:', 'Security Reconnaissance Scan'],
            ['Target:', self.scan.target],
            ['Scan Date:', self.scan.created_at.strftime("%Y-%m-%d %H:%M UTC") if self.scan.created_at else 'N/A'],
            ['Scan Type:', self.scan.scan_type or 'Full Scan'],
            ['Scan ID:', f"#{self.scan.id}"],
            ['Status:', self.scan.status.upper()],
            ['Duration:', f"{self.scan.duration:.1f}s" if self.scan.duration else 'N/A'],
            ['Generated:', datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")],
            ['Generated By:', 'KRYZENSYS Recon Platform'],
        ]
        if self.organization: cover_data.append(['Organization:', self.organization.name])
        cover_data.append(['Client:', self.user.full_name or self.user.username])
        cover_data.append(['Report Version:', '2.0'])
        t = Table(cover_data, colWidths=[5*cm, 11*cm])
        t.setStyle(TableStyle([
            ('FONT', (0, 0), (-1, -1), 'Helvetica', 11),
            ('FONT', (0, 0), (0, -1), 'Helvetica-Bold', 11),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.HexColor('#475569')),
            ('TEXTCOLOR', (1, 0), (1, -1), colors.HexColor('#1e293b')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LINEBELOW', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(t)
        story.append(Spacer(1, 2*cm))
        story.append(Paragraph("<b>CONFIDENTIAL</b>", ParagraphStyle('Confidential', parent=self.styles['Normal'], fontSize=10, textColor=colors.HexColor('#dc2626'), alignment=TA_CENTER, spaceAfter=8)))
        story.append(Paragraph("This report contains sensitive security information. Distribution is restricted to authorized personnel only.", ParagraphStyle('Disc', parent=self.styles['Normal'], fontSize=8, textColor=colors.HexColor('#64748b'), alignment=TA_CENTER)))
        return story

    def _build_executive_summary(self) -> List:
        story = []
        story.append(Paragraph("📊 Executive Summary", self.styles['CustomHeading1']))
        counts = self._severity_counts()
        total = sum(counts.values())
        risk_score = self._risk_score(counts)
        risk_level = "CRITICAL" if risk_score >= 80 else "HIGH" if risk_score >= 60 else "MEDIUM" if risk_score >= 40 else "LOW" if risk_score >= 20 else "MINIMAL"
        risk_color = colors.HexColor('#dc2626') if risk_score >= 80 else colors.HexColor('#ef4444') if risk_score >= 60 else colors.HexColor('#f59e0b') if risk_score >= 40 else colors.HexColor('#3b82f6') if risk_score >= 20 else colors.HexColor('#10b981')
        summary_text = f"""
        <b>Target:</b> {self.scan.target}<br/>
        <b>Total Findings:</b> {total}<br/>
        <b>Risk Score:</b> <font color="{risk_color.hexval()}">{risk_score}/100</font><br/>
        <b>Risk Level:</b> <font color="{risk_color.hexval()}"><b>{risk_level}</b></font><br/>
        <b>Critical Issues:</b> {counts.get(4, 0)}<br/>
        """
        story.append(Paragraph(summary_text, self.styles['CustomBody']))
        story.append(Spacer(1, 0.5*cm))
        story.append(Paragraph("Overview", self.styles['CustomHeading2']))
        overview = f"""
        A security reconnaissance scan was performed on <b>{self.scan.target}</b> on {self.scan.created_at.strftime("%B %d, %Y") if self.scan.created_at else 'N/A'}.
        The scan identified <b>{total} findings</b> across various security categories.
        Of these, <b>{counts.get(4, 0)} are critical</b> and <b>{counts.get(3, 0)} are high severity</b>, requiring immediate attention.
        The overall risk level is <b>{risk_level}</b>.
        """
        story.append(Paragraph(overview, self.styles['CustomBody']))
        story.append(Spacer(1, 0.5*cm))
        story.append(self._build_severity_chart())
        return story

    def _build_severity_chart(self) -> Drawing:
        counts = self._severity_counts()
        drawing = Drawing(400, 200)
        pie = Pie()
        pie.x, pie.y, pie.width, pie.height = 100, 30, 200, 140
        data = [counts.get(i, 0) for i in range(5)]
        if sum(data) == 0: data = [1]
        pie.data = data
        pie.labels = [f'{self.severity_names[i]}: {counts.get(i, 0)}' for i in range(5) if counts.get(i, 0) > 0]
        pie.slices.strokeWidth = 0.5
        for i, color in enumerate(self.severity_colors.values()):
            if i < len(pie.slices) and counts.get(i, 0) > 0:
                pie.slices[i].fillColor = color
        drawing.add(pie)
        return drawing

    def _build_target_info(self) -> List:
        story = []
        story.append(Paragraph("🎯 Target Information", self.styles['CustomHeading1']))
        target_data = [
            ['Field', 'Value'],
            ['Target', self.scan.target],
            ['Scan Type', self.scan.scan_type or 'Full'],
            ['Status', self.scan.status],
            ['Started', self.scan.created_at.strftime("%Y-%m-%d %H:%M:%S UTC") if self.scan.created_at else 'N/A'],
            ['Completed', self.scan.completed_at.strftime("%Y-%m-%d %H:%M:%S UTC") if hasattr(self.scan, 'completed_at') and self.scan.completed_at else 'N/A'],
            ['Duration', f"{self.scan.duration:.2f} seconds" if self.scan.duration else 'N/A'],
        ]
        t = Table(target_data, colWidths=[5*cm, 11*cm])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6366f1')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold', 11),
            ('FONT', (0, 1), (-1, -1), 'Helvetica', 10),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        story.append(t)
        return story

    def _build_severity_overview(self) -> List:
        story = []
        story.append(Paragraph("📈 Severity Distribution", self.styles['CustomHeading1']))
        counts = self._severity_counts()
        headers = ['Severity', 'Count', 'Percentage']
        rows = [headers]
        total = sum(counts.values()) or 1
        for i in range(5):
            count = counts.get(i, 0)
            pct = (count / total * 100) if total else 0
            rows.append([self.severity_names[i], str(count), f"{pct:.1f}%"])
        t = Table(rows, colWidths=[8*cm, 4*cm, 4*cm])
        style = [('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e293b')), ('TEXTCOLOR', (0, 0), (-1, 0), colors.white), ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold', 11), ('FONT', (0, 1), (-1, -1), 'Helvetica', 10), ('ALIGN', (1, 0), (-1, -1), 'CENTER'), ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1'))]
        for i in range(5):
            style.append(('TEXTCOLOR', (0, i+1), (0, i+1), self.severity_colors[i]))
            style.append(('FONT', (0, i+1), (0, i+1), 'Helvetica-Bold', 10))
        t.setStyle(TableStyle(style))
        story.append(t)
        return story

    def _build_findings(self) -> List:
        story = []
        story.append(Paragraph("🔍 Detailed Findings", self.styles['CustomHeading1']))
        if not self.findings:
            story.append(Paragraph("No findings were identified during this scan.", self.styles['CustomBody']))
            return story
        sorted_findings = sorted(self.findings, key=lambda f: -f.severity)
        for i, finding in enumerate(sorted_findings, 1):
            sev = self.severity_names.get(finding.severity, 'Info')
            story.append(KeepTogether([
                Paragraph(f"<b>Finding #{i}:</b> {finding.title}", self.styles['CustomHeading2']),
                Paragraph(f"<b>Severity:</b> <font color='{self.severity_colors[finding.severity].hexval()}'><b>{sev}</b></font> | <b>Category:</b> {finding.category} | <b>Source:</b> {finding.source or 'manual'}", self.styles['CustomBody']),
                Paragraph(f"<b>Description:</b>", self.styles['CustomBody']),
                Paragraph(finding.description or 'No description', self.styles['CustomBody']),
            ]))
            if finding.url:
                story.append(Paragraph(f"<b>URL:</b> <font name='Courier' size='8'>{finding.url}</font>", self.styles['CustomBody']))
            if finding.evidence:
                story.append(Paragraph(f"<b>Evidence:</b>", self.styles['CustomBody']))
                story.append(Paragraph(f"<font name='Courier' size='8'>{finding.evidence}</font>", self.styles['CodeStyle']))
            story.append(Spacer(1, 0.4*cm))
        return story

    def _build_recommendations(self) -> List:
        story = []
        story.append(Paragraph("✅ Recommendations", self.styles['CustomHeading1']))
        counts = self._severity_counts()
        recs = []
        if counts.get(4, 0) > 0:
            recs.append(("<b>URGENT:</b> Address all critical findings immediately. These represent severe security risks that could lead to system compromise.", colors.HexColor('#dc2626')))
        if counts.get(3, 0) > 0:
            recs.append(("<b>HIGH PRIORITY:</b> Remediate high-severity findings within 7 days. These issues pose significant risk to the organization.", colors.HexColor('#ef4444')))
        if counts.get(2, 0) > 0:
            recs.append(("<b>MEDIUM:</b> Plan remediation for medium-severity issues within 30 days.", colors.HexColor('#f59e0b')))
        if counts.get(1, 0) > 0:
            recs.append(("<b>LOW:</b> Address low-severity issues as part of regular maintenance.", colors.HexColor('#3b82f6')))
        recs.append(("<b>Best Practices:</b> Implement continuous security scanning, regular patch management, security awareness training, and incident response procedures.", colors.HexColor('#10b981')))
        for rec, color in recs:
            story.append(Paragraph(f"• {rec}", ParagraphStyle('Rec', parent=self.styles['CustomBody'], leftIndent=15, textColor=color, spaceAfter=8)))
        return story

    def _build_appendix(self) -> List:
        story = []
        story.append(Paragraph("📎 Appendix", self.styles['CustomHeading1']))
        story.append(Paragraph("Methodology", self.styles['CustomHeading2']))
        story.append(Paragraph("This scan was performed using KRYZENSYS Recon Platform v2.0, which employs industry-standard security testing techniques including:", self.styles['CustomBody']))
        for method in ["• Active network scanning and service detection", "• Web application security testing (OWASP Top 10)", "• DNS enumeration and subdomain discovery", "• SSL/TLS configuration analysis", "• Open port and service enumeration", "• Vulnerability database correlation (CVE, CWE)", "• ML-based anomaly detection"]:
            story.append(Paragraph(method, ParagraphStyle('Method', parent=self.styles['CustomBody'], leftIndent=15, spaceAfter=4)))
        story.append(Spacer(1, 0.5*cm))
        story.append(Paragraph("Disclaimer", self.styles['CustomHeading2']))
        story.append(Paragraph("This report is provided 'as is' for informational purposes only. KRYZENSYS makes no warranties regarding the accuracy or completeness of the information. The user is responsible for verifying findings and implementing appropriate remediation measures.", self.styles['CustomBody']))
        story.append(Spacer(1, 0.5*cm))
        story.append(Paragraph("Contact", self.styles['CustomHeading2']))
        story.append(Paragraph("For questions or clarification: <b>security@recon.kryzensys.com</b> | <b>https://recon.kryzensys.com</b>", self.styles['CustomBody']))
        return story

    def _draw_footer(self, canvas, doc):
        canvas.saveState()
        canvas.setFont('Helvetica', 8)
        canvas.setFillColor(colors.HexColor('#94a3b8'))
        page_num = canvas.getPageNumber()
        canvas.drawString(2*cm, 1*cm, f"KRYZENSYS Recon Platform - Confidential Report - {self.scan.target}")
        canvas.drawRightString(A4[0] - 2*cm, 1*cm, f"Page {page_num}")
        canvas.drawString(2*cm, 0.6*cm, f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
        canvas.drawRightString(A4[0] - 2*cm, 0.6*cm, f"Scan ID: #{self.scan.id}")
        canvas.restoreState()

    def _severity_counts(self) -> Dict:
        counts = {0: 0, 1: 0, 2: 0, 3: 0, 4: 0}
        for f in self.findings: counts[f.severity] = counts.get(f.severity, 0) + 1
        return counts

    def _risk_score(self, counts: Dict) -> int:
        weights = {0: 0, 1: 1, 2: 5, 3: 15, 4: 30}
        score = sum(counts.get(i, 0) * weights[i] for i in range(5))
        return min(100, score)


def generate_scan_pdf(scan_id: int, output_path: str = None) -> bytes:
    """Convenience function to generate PDF"""
    scan = Scan.query.get(scan_id)
    if not scan: raise ValueError(f"Scan {scan_id} not found")
    user = User.query.get(scan.user_id)
    org = None
    if hasattr(user, 'organization_id') and user.organization_id:
        org = Organization.query.get(user.organization_id)
    generator = PDFReportGenerator(scan, user, org)
    return generator.generate(output_path)
